name: Build and Update README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: nxrmqlly/nxrmqlly

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
          architecture: x64

      - name: Install required dependencies
        run: python -m pip install -r requirements.txt

      - name: Generate README content
        run: |
          python build_readme.py

      - name: Commit and push changes if README is updated
        run: |
          git diff --exit-code || (
            git config --global user.email "nxrmqlly-readme-bot@example.com"
            git config --global user.name "README-BOT"
            git add README.md
            git commit -m "Update README content"
            git push
          )
